# Generated by Django 2.1.7 on 2019-03-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedi_academy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='planet',
            new_name='questions',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
