# Generated by Django 2.1.7 on 2019-03-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedi_academy_app', '0002_auto_20190331_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='questions',
        ),
        migrations.AddField(
            model_name='trial',
            name='question1',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='trial',
            name='question2',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='trial',
            name='question3',
            field=models.CharField(default='', max_length=256),
        ),
    ]
