# Generated by Django 2.1.7 on 2019-04-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedi_academy_app', '0004_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedi_academy_app.Jedi')),
                ('padawans', models.ManyToManyField(to='jedi_academy_app.Candidate')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
